In [62]:
#Libraries
import os
import pandas as pd
from urllib.request import urlopen as uReq
from bs4 import BeautifulSoup as soup

In [26]:
#Initialising

url = 'https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_suicide_rate'
uClient = uReq(url)
page_html = uClient.read()
uClient.close()

page_soup = soup(page_html,'html.parser')
table = page_soup.findAll('table', {'class':'wikitable sortable'})[0]

#Headers
headers = []
for title in table.tr.findAll('th'):
    headers.append(title.text.strip())
headers

['Rank', 'State', 'Suicide Rate (per 1 lakh) 2015[4]']

In [58]:
# Extracting data for each row
rank = []
state = []
suicide = []

for row in table.findAll('tr')[1:]:
    cell = row.findAll('td')
    rank.append(cell[0].text)
    state.append(cell[1].text)
    suicide.append(float(cell[2].text.strip()))

In [71]:
#Reshaping and formating data
data = pd.DataFrame([rank, state, suicide]).T
data.columns = headers

In [83]:
#Let's have a look at the results
data

   Rank                        State Suicide Rate (per 1 lakh) 2015[4]
0     1                       Sikkim                              37.5
1     2                 Chhattisgarh                              27.7
2     2                    Telangana                              27.7
3     4                   Tamil Nadu                              22.8
4     5                       Kerala                              21.6
5     6                      Tripura                              19.6
6     7                    Karnataka                              17.4
7     8                  West Bengal                              15.7
8     9                          Goa                              15.4
9    10                  Maharashtra                              14.2
10   11               Madhya Pradesh                              13.3
11   12                      Haryana                                13
12   13               Andhra Pradesh                              12.1
13   14                      Mizoram                              11.7
14   15                      Gujarat                              11.6
15   16            Arunachal Pradesh                              10.4
16   17                        Assam                                10
17   18                       Odisha                               9.7
18   19             Himachal Pradesh                               7.7
19   20                    Meghalaya                               6.2
20   21                    Rajasthan                               4.8
21   22                  Uttarakhand                               4.5
22   23                       Punjab                               3.6
23   24            Jammu and Kashmir                                 3
24   25                    Jharkhand                               2.5
25   26                Uttar Pradesh                                 0
26   27                      Manipur                               1.4
27   28                     Nagaland                               0.9
28   29                        Bihar                               0.5
29  UT1                   Puducherry                              43.2
30  UT2  Andaman and Nicobar Islands                              28.9
31  UT3       Dadra and Nagar Haveli                              25.4
32  UT4                Daman and Diu                              11.8
33  UT5                        Delhi                               8.8
34  UT6                   Chandigarh                               6.9
35  UT7                  Lakshwadeep                               6.3

In [84]:
#Saving data

data.to_csv('sucides.csv', index=False)